spring:
  application:
    name: "blog-search-service"
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
    loggers:
      enabled: true
  metrics:
    tags:
      application: "${spring.application.name}"
      profiles: "${spring.profiles.active}"

blog-search:
  kakao:
    enabled: true
    access-token: "85dcce19a42aee743cd930539fa77148"
    base-url: "https://dapi.kakao.com"
  naver:
    enabled: true
    client-id: "tmSzF3XCZREtNFARaU6Z"
    client-secret: "gFFnc5mGcb"
    base-url: "https://openapi.naver.com"